### ISSUE TITLE
license for this project

### ISSUE THREAD

**Issue by strumswell** [SertoID/veramo-aws-kms#1]
I was wondering what license this project has. We potentially want to extend and use it.

Looking forward for you answer. :)

**Comment by italobb** [comment]
@strumswell It's `Apache License 2.0`. We'll update it in the project to make it clear.

**Comment by italobb** [comment]
@strumswell License information updated. 
Feel free to move forward extending it. 
I suggest upgrading Veramo version first.

**Comment by strumswell** [comment]
Thanks!
